[build-system]
requires = ["setuptools"] # setuptools and wheel are necessary for the build

[project]
name = "nuphysim"
version = "0.1"
description = 'A package to analyse AFM via FEM simulations'
authors = [
    {name = "J. Giblin-Burnham", email = "j.giblin-burnham@hotmail.com"}
]
readme = "README.md"
homepage = 'https://neuron-multiphysics-simulations.readthedocs.io/en/latest/index.html'

[project.urls]
Source = "myfancywebsite.com"'https://neuron-multiphysics-simulations.readthedocs.io/en/latest/index.html'


[project.scripts] # Define scripts here if you have any

[project.dependencies]
numpy = "*"
matplotlib = "*"
scipy = "*"
absl-py = "*"
biopython = "*"
keras = "*"
pypdf = "*"
pypdf2 = "*"
scp = "*"
paramiko = "*"
sphinx_rtd_theme = "*"

[project.optional-dependencies] # Define optional dependencies here if you have any